---
title: "dnds"
format: html
---

```{r}

library(ape)
library(tidyverse)
library(readr)
library(phylolm)
library(devtools)
library(ClockstaRX)
library(mice)


setwd("/Users/macbook/Desktop/Phylogenetics/ruminants/ruminants_project")

ruminants_trees <- load("data/clean_dnds_ratio_trees.Rdata")
rumsptimetr <- read.tree("data/rumsptimetr.nwk")
bio_traits_log <- read_csv("data/bio_traits_log.csv",  n_max = 51)[, 1:11]
final_bio_traits <- read_csv("data/bio_traits_modified_new.csv",  n_max = 51)[, 1:8]
final_bio_traits_log <- read_csv("data/bio_traits_modified_log_new.csv",  n_max = 51)[, 1:8]

domesticates_tips <- c("goat", "Sheep","Yak", "Cattle", "Reindeer")
final_bio_traits_motif_wild <- final_bio_traits_log %>%
  filter(!Species %in% domesticates_tips)


```

```{r}

#Remove Orcinus orca (KillerWhal) from all trees
tree <- ratio_trees_filtered[[1]] 
tip_labels <- tree$tip.label #look at tip labels for first tree
print(tip_labels)

ratio_trees <- lapply(ratio_trees_filtered, function(tree) {
    drop.tip(tree, "KillerWhal")  })

rumsptimetr_filtered <- drop.tip(rumsptimetr, "KillerWhal")

tip_labels <- rumsptimetr_filtered$tip.label #look at tip labels for first tree
print(tip_labels)

```

#REMOVE DOMESTICATES
```{r}

#remove domesticates
domesticates_tips <- c("goat", "Sheep","Yak", "Cattle", "Reindeer") #reindeer is semi domesticated

rum12_filtered_wild <- lapply(rum12_filtered, function(tree) {
    drop.tip(tree, domesticates_tips)
})

rum3_filtered_wild <- lapply(rum3_filtered, function(tree) {
    drop.tip(tree, domesticates_tips)  })

rumrand_filtered_wild <- lapply(rumrand_filtered, function(tree) {
    drop.tip(tree, domesticates_tips)  })

rumsptr_filtered_wild <- drop.tip(rumsptr_filtered, domesticates_tips) 

rumsptimetr_filtered_wild <- drop.tip(rumsptimetr_filtered, domesticates_tips)

tree <- rum12_filtered_wild[[1]] 
tip_labels <- tree$tip.label #look at tip labels for first tree
print(tip_labels)



#wild bio_traits
bio_traits_wild <- bio_traits %>%
  filter(!Species %in% domesticates_tips)

bio_traits_motif_wild <- bio_traits_updated_log %>%
  filter(!Species %in% domesticates_tips)

```

```{r}

library(ape)

folder_name <- "/Users/macbook/Desktop/Phylogenetics/ruminants/dnds_pml/dn_erable_output"

setwd(folder_name)
nwk_files <- list.files(pattern = "\\.nwk$")
dn_trees <- lapply(nwk_files, read.tree)
gene_names <- sub("_erable_dn\\.length$", "", tools::file_path_sans_ext(nwk_files))
names(dn_trees) <- gene_names
class(dn_trees) <- "multiPhylo"

folder_name <- "/Users/macbook/Desktop/Phylogenetics/ruminants/dnds_pml/ds_erable_output"
setwd(folder_name)
nwk_files <- list.files(pattern = "\\.nwk$")
ds_trees <- lapply(nwk_files, read.tree)
gene_names2 <- sub("_erable_ds\\.length$", "", tools::file_path_sans_ext(nwk_files))
names(ds_trees) <- gene_names2
class(ds_trees) <- "multiPhylo"

save(dn_trees, ds_trees, file="/Users/macbook/Desktop/Phylogenetics/ruminants/ruminants_project/data/dnds_trees.Rdata")
```



##### readme


```{bash}


#creating the multiphylo objects

Rscript nwks_scripts.R






```

#### creating ratio

```{r}

library(ape)

trees <- "/Users/macbook/Desktop/Phylogenetics/ruminants/ruminants_project/data/dnds_trees.Rdata"

load(trees)

ratio_trees <- list()
epsilon <- 1e-6

gene_list <- names(dn_trees_clean)

for (gene in gene_list) {
  dn_tree <- dn_trees_clean[[gene]]
  ds_tree <- ds_trees_clean[[gene]]
  
  if (!all(dn_tree$edge == ds_tree$edge)) {
    warning(paste("Topology mismatch in", gene))
    next
  }

  ds_lengths <- ds_tree$edge.length
  ds_lengths[ds_lengths == 0] <- epsilon

  dn_lengths <- dn_tree$edge.length
  dn_lengths[dn_lengths == 0] <- epsilon

  ratio_lengths <- dn_lengths / ds_lengths

  if (any(!is.finite(ratio_lengths))) {
    next 
  }
  ratio_tree <- dn_tree
  ratio_tree$edge.length <- ratio_lengths
  ratio_trees[[gene]] <- ratio_tree
}

ratio_trees <- Filter(Negate(is.null), ratio_trees)
class(ratio_trees) <- "multiPhylo"

```

```{r}

library(ape)
library(tidyverse)
library(readr)
library(phylolm)
library(devtools)
library(ClockstaRX)

setwd("/Users/macbook/Desktop/Phylogenetics/ruminants/ruminants_project")
output_dir <-"outputs"

ruminants_trees <- load("data/clean_dnds_ratio_trees.Rdata")
rumsptimetr <- read.tree("data/rumsptimetr.nwk")

#remove outgroup
dnds_trees <- lapply(ratio_trees_filtered, function(tree) {
    drop.tip(tree, "KillerWhal")  })
rumsptimetr_filtered <- drop.tip(rumsptimetr, "KillerWhal")

#perform clockstarx
dnds_ratio_clock_analysis <- diagnose.clocks(loctrs = dnds_trees, 
    sptr = rumsptimetr_filtered, 
    sp.time.tree=TRUE,
    ncore = 10,
    clustering.boot.samps = 5,
    mds = FALSE,
    pdf.file = file.path(output_dir,"dnds_ratio_ncore10_mdsf_b5.clockstarx")
    )

save(dnds_ratio_clock_analysis, file = file.path(output_dir, "dnds_ratio_clock_analysis.RData"))



```